/// Flutter icons SocialLogos
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialLogos
///      fonts:
///       - asset: fonts/SocialLogos.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class SocialLogos {
  SocialLogos._();

  static const _kFontFam = 'SocialLogos';
  static const String? _kFontPkg = null;

  static const IconData whatsapp = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitterx = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
